shell /bin/zsh
font_family      Annotation Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

cursor_shape          beam
cursor_blink_interval 0
copy_on_select        yes
confirm_os_window_close 0