#!/usr/bin/env python3
"""Generate ~/.config/gtk-4.0/gtk.css from the active quickshell theme.

Overrides libadwaita's named colours so GTK4/libadwaita apps (Nautilus, etc.)
take the quickshell palette. Not live -- libadwaita reads gtk.css at startup, so
apps pick up a new palette on their next launch (the light/dark *variant* still
switches live via theme-variant.sh; this adds the exact colours on top).

Resolves the theme the way the shell does: config.json deep-merged with the host
file, then the theme JSON. Run on theme commit; optional arg forces a theme name.
"""
import json, os, socket, sys

HOME = os.path.expanduser("~")

def qs_dir():
    here = os.path.dirname(os.path.abspath(__file__))
    for c in (os.path.join(HOME, ".config/quickshell"),
              os.path.join(here, "..", "..", "quickshell")):
        if os.path.isfile(os.path.join(c, "config.json")):
            return os.path.abspath(c)
    sys.exit("gtk-palette: no quickshell config.json found")

def load(p):
    with open(p, encoding="utf-8") as f:
        return json.load(f)

def active_name(qs):
    name = load(os.path.join(qs, "config.json")).get("theme", {}).get("name", "Nord")
    host = os.path.join(qs, f"config.{socket.gethostname()}.json")
    if os.path.isfile(host):
        name = load(host).get("theme", {}).get("name", name)
    return name

# libadwaita named colour  <-  quickshell palette token
MAP = {
    "accent_color":              "accent",
    "accent_bg_color":           "accent",
    "accent_fg_color":           "background",
    "window_bg_color":           "background",
    "window_fg_color":           "text",
    "view_bg_color":             "background",
    "view_fg_color":             "text",
    "headerbar_bg_color":        "surface",
    "headerbar_fg_color":        "text",
    "headerbar_backdrop_color":  "background",
    "sidebar_bg_color":          "surface",
    "sidebar_fg_color":          "text",
    "sidebar_backdrop_color":    "background",
    "secondary_sidebar_bg_color":"surface",
    "secondary_sidebar_fg_color":"text",
    "card_bg_color":             "surface",
    "card_fg_color":             "text",
    "popover_bg_color":          "surface",
    "popover_fg_color":          "text",
    "dialog_bg_color":           "surface",
    "dialog_fg_color":           "text",
}

def main():
    qs = qs_dir()
    name = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else active_name(qs)
    p = load(os.path.join(qs, "themes", f"{name}.json"))
    w = max(len(k) for k in MAP)
    lines = [f"/* generated by gtk-palette.py from quickshell theme: {name} */"]
    lines += [f"@define-color {named.ljust(w)} {p[tok]};" for named, tok in MAP.items()]
    out_dir = os.path.join(HOME, ".config/gtk-4.0")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "gtk.css"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"gtk-palette: wrote {out_dir}/gtk.css <- {name}")

if __name__ == "__main__":
    main()
